language: ruby

rvm:
  - 2.1.0	

notifications:
  email:
    recipients:
      - saddy666@gmail.com
    on_success: change
    on_failure: change

before_script:
  - psql -c "CREATE USER ann WITH PASSWORD '';" -U postgres