language: ruby

rvm:
  - 2.1.0	

notifications:
  email:
    recipients:
      - saddy666@gmail.com
    on_success: change
    on_failure: change

before_script:
  - psql -c 'create database depot_test;' -U postgres