development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  pool: 5
  username: ann
  password:
 

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  pool: 5
  username: ann
  password:
