development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  pool: 5
  username: postgres
  password:
 

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: depot_production
  pool: 5
  username: postgres
  password:
